1. Go to https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016 and download the data

In [1]:
### 2. Using command line rename the downloaded file to suicide_rates.csv then move the file (command line) to your repository 
# `use 'mv' `

!ls
!unzip 'suicide-rates-overview-1985-to-2016.zip'
!ls

2_1_visualization_matplotlib.md         coba_week_2_warm_up_lambda.ipynb
2_2_apply_lambda_gb_plt.md              master.csv
2_3_simulation_np_random_n_dict.md      plots
2_4_histogram_lr_creation.md            solutions
2_5_cat_n_normalize.md                  suicide-rates-overview-1985-to-2016.zip
2_6_multi_reg_cross_val.md              suicide_rates.csv
Archive:  suicide-rates-overview-1985-to-2016.zip
replace master.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C
2_1_visualization_matplotlib.md         coba_week_2_warm_up_lambda.ipynb
2_2_apply_lambda_gb_plt.md              master.csv
2_3_simulation_np_random_n_dict.md      plots
2_4_histogram_lr_creation.md            solutions
2_5_cat_n_normalize.md                  suicide-rates-overview-1985-to-2016.zip
2_6_multi_reg_cross_val.md              suicide_rates.csv

In [ ]:
!mv master.csv suicide_rates.csv

In [7]:
ls

2_1_visualization_matplotlib.md
2_2_apply_lambda_gb_plt.md
2_3_simulation_np_random_n_dict.md
2_4_histogram_lr_creation.md
2_5_cat_n_normalize.md
2_6_multi_reg_cross_val.md
coba_week_2_warm_up_lambda.ipynb
master.csv
plots/
solutions/
suicide-rates-overview-1985-to-2016.zip
suicide_rates.csv

In [10]:
import pandas as pd

In [11]:
### 3. Load the data into pandas df
df = pd.read_csv('master.csv')
df

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
10,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
12,Albania,1988,female,75+ years,2,36400,5.49,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
13,Albania,1988,male,15-24 years,17,319200,5.33,Albania1988,NaN,"2,126,000,000",769,Generation X
14,Albania,1988,male,75+ years,1,22300,4.48,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
15,Albania,1988,male,35-54 years,14,314100,4.46,Albania1988,NaN,"2,126,000,000",769,Silent
16,Albania,1988,male,55-74 years,4,140200,2.85,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
17,Albania,1988,female,15-24 years,8,295600,2.71,Albania1988,NaN,"2,126,000,000",769,Generation X
18,Albania,1988,female,55-74 years,3,147500,2.03,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
19,Albania,1988,female,25-34 years,5,262400,1.91,Albania1988,NaN,"2,126,000,000",769,Boomers
20,Albania,1988,male,25-34 years,5,279900,1.79,Albania1988,NaN,"2,126,000,000",769,Boomers
21,Albania,1988,female,35-54 years,4,284500,1.41,Albania1988,NaN,"2,126,000,000",769,Silent
22,Albania,1988,female,5-14 years,0,317200,0.00,Albania1988,NaN,"2,126,000,000",769,Generation X
23,Albania,1988,male,5-14 years,0,345000,0.00,Albania1988,NaN,"2,126,000,000",769,Generation X
24,Albania,1989,male,75+ years,2,22500,8.89,Albania1989,NaN,"2,335,124,988",833,G.I. Generation
25,Albania,1989,male,25-34 years,18,283600,6.35,Albania1989,NaN,"2,335,124,988",833,Boomers
26,Albania,1989,male,35-54 years,15,318400,4.71,Albania1989,NaN,"2,335,124,988",833,Silent
27,Albania,1989,male,55-74 years,6,142100,4.22,Albania1989,NaN,"2,335,124,988",833,G.I. Generation
28,Albania,1989,male,15-24 years,12,323500,3.71,Albania1989,NaN,"2,335,124,988",833,Generation X
29,Albania,1989,female,35-54 years,7,288600,2.43,Albania1989,NaN,"2,335,124,988",833,Silent
...,...,...,...,...,...,...,...,...,...,...,...,...
27790,Uzbekistan,2012,female,25-34 years,148,2556673,5.79,Uzbekistan2012,0.668,"51,821,573,338",1964,Millenials
27791,Uzbekistan,2012,female,35-54 years,89,3474788,2.56,Uzbekistan2012,0.668,"51,821,573,338",1964,Generation X
27792,Uzbekistan,2012,male,5-14 years,67,2701361,2.48,Uzbekistan2012,0.668,"51,821,573,338",1964,Generation Z
27793,Uzbekistan,2012,female,55-74 years,25,1283060,1.95,Uzbekistan2012,0.668,"51,821,573,338",1964,Boomers
27794,Uzbekistan,2012,female,75+ years,4,338557,1.18,Uzbekistan2012,0.668,"51,821,573,338",1964,Silent
27795,Uzbekistan,2012,female,5-14 years,16,2578408,0.62,Uzbekistan2012,0.668,"51,821,573,338",1964,Generation Z
27796,Uzbekistan,2013,male,35-54 years,481,3346411,14.37,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation X
27797,Uzbekistan,2013,male,25-34 years,328,2644648,12.40,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27798,Uzbekistan,2013,female,15-24 years,323,3039740,10.63,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27799,Uzbekistan,2013,male,15-24 years,320,3171202,10.09,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27800,Uzbekistan,2013,male,55-74 years,119,1202790,9.89,Uzbekistan2013,0.672,"57,690,453,461",2150,Boomers
27801,Uzbekistan,2013,male,75+ years,13,221002,5.88,Uzbekistan2013,0.672,"57,690,453,461",2150,Silent
27802,Uzbekistan,2013,female,25-34 years,146,2647820,5.51,Uzbekistan2013,0.672,"57,690,453,461",2150,Millenials
27803,Uzbekistan,2013,female,35-54 years,99,3547895,2.79,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation X
27804,Uzbekistan,2013,female,75+ years,8,345180,2.32,Uzbekistan2013,0.672,"57,690,453,461",2150,Silent
27805,Uzbekistan,2013,male,5-14 years,61,2720938,2.24,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation Z
27806,Uzbekistan,2013,female,55-74 years,21,1356298,1.55,Uzbekistan2013,0.672,"57,690,453,461",2150,Boomers
27807,Uzbekistan,2013,female,5-14 years,31,2595000,1.19,Uzbekistan2013,0.672,"57,690,453,461",2150,Generation Z
27808,Uzbekistan,2014,male,35-54 years,519,3421300,15.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27809,Uzbekistan,2014,male,25-34 years,318,2739150,11.61,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27810,Uzbekistan,2014,female,15-24 years,347,2992817,11.59,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27811,Uzbekistan,2014,male,55-74 years,144,1271111,11.33,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers
27812,Uzbekistan,2014,male,15-24 years,347,3126905,11.10,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27813,Uzbekistan,2014,male,75+ years,17,224995,7.56,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27814,Uzbekistan,2014,female,25-34 years,162,2735238,5.92,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [20]:
### 4. Pick only rows where country starts with U `use apply and lambda`
df[df['country'].apply(lambda x: x.startswith('U'))]

In [22]:
### 5. Get the names of unique countries left `use pd.unique` 
print(df[~df['country'].apply(lambda x: x.startswith('U'))]['country'].unique())

['Albania' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia'
 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Barbados' 'Belarus' 'Belgium'
 'Belize' 'Bosnia and Herzegovina' 'Brazil' 'Bulgaria' 'Cabo Verde'
 'Canada' 'Chile' 'Colombia' 'Costa Rica' 'Croatia' 'Cuba' 'Cyprus'
 'Czech Republic' 'Denmark' 'Dominica' 'Ecuador' 'El Salvador' 'Estonia'
 'Fiji' 'Finland' 'France' 'Georgia' 'Germany' 'Greece' 'Grenada'
 'Guatemala' 'Guyana' 'Hungary' 'Iceland' 'Ireland' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Kazakhstan' 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Latvia'
 'Lithuania' 'Luxembourg' 'Macau' 'Maldives' 'Malta' 'Mauritius' 'Mexico'
 'Mongolia' 'Montenegro' 'Netherlands' 'New Zealand' 'Nicaragua' 'Norway'
 'Oman' 'Panama' 'Paraguay' 'Philippines' 'Poland' 'Portugal'
 'Puerto Rico' 'Qatar' 'Republic of Korea' 'Romania' 'Russian Federation'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and Grenadines'
 'San Marino' 'Serbia' 'Seychelles' 'Singapore' 'Slovakia' 'Slovenia'
 'South Africa' 'Spain' 'Sri Lanka' 'Suriname' 'Sweden' 'Switzerland'
 'Thailand' 'Trinidad and Tobago' 'Turkey' 'Turkmenistan']

In [ ]:
### [Thoughts]: how would that be useful if we have duplicated values in a dataset?

In [25]:
###  5.5. pick only 'United States' (without using apply or lambda - try using indexing)
df_us = df[df['country']=='United States']

In [27]:
### 6. Group by age column and sum # suicides
df_us.groupby(['age']).sum()

,year,suicides_no,population,suicides/100k pop,HDI for year,gdp_per_capita ($)
age,,,,,,
15-24 years,124000,141679,1238381995,703.45,17.832,2434716
25-34 years,124000,182047,1277625343,878.69,17.832,2434716
35-54 years,124000,380917,2371577220,994.52,17.832,2434716
5-14 years,124000,8923,1205493232,45.47,17.832,2434716
55-74 years,124000,224770,1460664960,988.47,17.832,2434716
75+ years,124000,95677,500284451,1530.37,17.832,2434716

In [46]:
### 7. Change the age column to a categorical one 
# `use astype`

df_us['age'] = df_us['age'].astype('category')

/Users/physics/anaconda/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [53]:
colnames = df_us['age'].unique()
print(sorted(colnames))

['15-24 years', '25-34 years', '35-54 years', '5-14 years', '55-74 years', '75+ years']

In [68]:
### 8. Re-order the categories so that 5-14 years appears first 
# df_us.sort_values(['age'], ascending=True) `use cat.reorder_categories`
df_3 = df.copy()
df_3["age"] = pd.Categorical(df_3['age'], ['5-14 years', '15-24 years', '25-34 years', '35-54 years', '55-74 years', '75+ years'])
df_3.sort_values("age")

# cat.reorder_categories

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
25563,Trinidad and Tobago,2005,male,5-14 years,0,97155,0.00,Trinidad and Tobago2005,0.753,"15,982,282,462",13258,Millenials
3990,Belize,2002,male,5-14 years,0,33881,0.00,Belize2002,NaN,"932,551,850",4161,Millenials
13447,Japan,1991,female,5-14 years,14,7536000,0.19,Japan1991,NaN,"3,584,420,077,101",30688,Millenials
26222,Ukraine,1999,male,5-14 years,79,3467900,2.28,Ukraine1999,NaN,"31,580,639,045",666,Millenials
16815,Mexico,2005,female,5-14 years,57,11456090,0.50,Mexico2005,0.722,"877,476,221,382",9071,Millenials
3986,Belize,2002,female,5-14 years,1,33244,3.01,Belize2002,NaN,"932,551,850",4161,Millenials
13446,Japan,1991,male,5-14 years,22,7928000,0.28,Japan1991,NaN,"3,584,420,077,101",30688,Millenials
26223,Ukraine,1999,female,5-14 years,14,3324800,0.42,Ukraine1999,NaN,"31,580,639,045",666,Millenials
8399,Estonia,1998,male,5-14 years,5,103157,4.85,Estonia1998,NaN,"5,617,109,245",4250,Millenials
3979,Belize,2001,male,5-14 years,0,32991,0.00,Belize2001,NaN,"871,860,600",4013,Millenials
8401,Estonia,1998,female,5-14 years,1,98422,1.02,Estonia1998,NaN,"5,617,109,245",4250,Millenials
3976,Belize,2001,female,5-14 years,0,32384,0.00,Belize2001,NaN,"871,860,600",4013,Millenials
16825,Mexico,2006,male,5-14 years,114,11875780,0.96,Mexico2006,NaN,"975,387,131,716",9906,Millenials
24451,Sweden,1993,female,5-14 years,0,494200,0.00,Sweden1993,NaN,"209,950,792,713",25880,Millenials
21079,Russian Federation,2000,female,5-14 years,103,9543220,1.08,Russian Federation2000,NaN,"259,708,496,267",1879,Millenials
16827,Mexico,2006,female,5-14 years,61,11508120,0.53,Mexico2006,NaN,"975,387,131,716",9906,Millenials
21078,Russian Federation,2000,male,5-14 years,404,9986252,4.05,Russian Federation2000,NaN,"259,708,496,267",1879,Millenials
24450,Sweden,1993,male,5-14 years,1,520500,0.19,Sweden1993,NaN,"209,950,792,713",25880,Millenials
8389,Estonia,1997,female,5-14 years,0,101713,0.00,Estonia1997,NaN,"5,066,240,419",3806,Millenials
3967,Belize,2000,male,5-14 years,0,32066,0.00,Belize2000,0.683,"832,072,450",3960,Millenials
16813,Mexico,2005,male,5-14 years,98,11833699,0.83,Mexico2005,0.722,"877,476,221,382",9071,Millenials
3999,Belize,2003,male,5-14 years,1,34739,2.88,Belize2003,NaN,"990,374,050",4289,Millenials
24463,Sweden,1994,male,5-14 years,0,534800,0.00,Sweden1994,NaN,"226,079,963,712",27658,Millenials
24462,Sweden,1994,female,5-14 years,2,507200,0.39,Sweden1994,NaN,"226,079,963,712",27658,Millenials
21091,Russian Federation,2001,female,5-14 years,114,8998521,1.27,Russian Federation2001,NaN,"306,602,673,980",2229,Millenials
26210,Ukraine,1998,male,5-14 years,53,3605000,1.47,Ukraine1998,NaN,"41,883,241,472",879,Millenials
4014,Belize,2004,male,5-14 years,0,35566,0.00,Belize2004,NaN,"1,057,845,500",4449,Millenials
26211,Ukraine,1998,female,5-14 years,25,3462400,0.72,Ukraine1998,NaN,"41,883,241,472",879,Millenials
4012,Belize,2004,female,5-14 years,0,34909,0.00,Belize2004,NaN,"1,057,845,500",4449,Millenials
22422,Singapore,1986,male,5-14 years,2,213700,0.94,Singapore1986,NaN,"18,569,292,305",7805,Generation X
...,...,...,...,...,...,...,...,...,...,...,...,...
23172,Slovenia,2006,female,75+ years,21,92452,22.71,Slovenia2006,NaN,"39,587,732,029",20634,Silent
11604,Hungary,2011,male,75+ years,200,239506,83.51,Hungary2011,0.823,"140,782,064,609",14827,Silent
23168,Slovenia,2006,male,75+ years,48,41789,114.86,Slovenia2006,NaN,"39,587,732,029",20634,Silent
11607,Hungary,2011,female,75+ years,122,503846,24.21,Hungary2011,0.823,"140,782,064,609",14827,Silent
11616,Hungary,2012,male,75+ years,233,232766,100.10,Hungary2012,0.823,"127,856,647,108",13525,Silent
23197,Slovenia,2008,female,75+ years,17,99156,17.14,Slovenia2008,NaN,"55,589,849,128",28599,Silent
11427,Hungary,1996,female,75+ years,224,355446,63.02,Hungary1996,NaN,"46,659,796,773",4792,G.I. Generation
11532,Hungary,2005,male,75+ years,269,222774,120.75,Hungary2005,0.802,"113,035,361,317",11764,Silent
11520,Hungary,2004,male,75+ years,262,218145,120.10,Hungary2004,NaN,"104,066,609,518",10806,Silent
11439,Hungary,1997,female,75+ years,199,369640,53.84,Hungary1997,NaN,"47,290,180,589",4856,G.I. Generation
11448,Hungary,1998,male,75+ years,238,189405,125.66,Hungary1998,NaN,"48,770,466,839",5010,G.I. Generation
23231,Slovenia,2011,female,75+ years,20,106590,18.76,Slovenia2011,0.877,"51,290,792,018",26377,Silent
11451,Hungary,1998,female,75+ years,185,384001,48.18,Hungary1998,NaN,"48,770,466,839",5010,G.I. Generation
23228,Slovenia,2011,male,75+ years,56,53258,105.15,Slovenia2011,0.877,"51,290,792,018",26377,Silent
11460,Hungary,1999,male,75+ years,302,185652,162.67,Hungary1999,NaN,"49,170,434,391",5147,G.I. Generation
11463,Hungary,1999,female,75+ years,184,378946,48.56,Hungary1999,NaN,"49,170,434,391",5147,G.I. Generation
11472,Hungary,2000,male,75+ years,272,188686,144.15,Hungary2000,0.769,"47,310,623,887",4966,G.I. Generation
23222,Slovenia,2010,female,75+ years,12,104453,11.49,Slovenia2010,0.876,"48,013,606,745",24689,Silent
11475,Hungary,2000,female,75+ years,199,387228,51.39,Hungary2000,0.769,"47,310,623,887",4966,G.I. Generation
11484,Hungary,2001,male,75+ years,276,205366,134.39,Hungary2001,NaN,"53,821,315,066",5546,Silent
23216,Slovenia,2010,male,75+ years,49,50887,96.29,Slovenia2010,0.876,"48,013,606,745",24689,Silent
11487,Hungary,2001,female,75+ years,157,419870,37.39,Hungary2001,NaN,"53,821,315,066",5546,Silent
11496,Hungary,2002,male,75+ years,254,209732,121.11,Hungary2002,NaN,"67,716,887,203",6995,Silent
11499,Hungary,2002,female,75+ years,149,430724,34.59,Hungary2002,NaN,"67,716,887,203",6995,Silent
11508,Hungary,2003,male,75+ years,236,213793,110.39,Hungary2003,NaN,"85,324,771,841",8840,Silent
23208,Slovenia,2009,female,75+ years,21,101714,20.65,Slovenia2009,NaN,"50,244,793,832",25872,Silent
11511,Hungary,2003,female,75+ years,159,440470,36.10,Hungary2003,NaN,"85,324,771,841",8840,Silent
23204,Slovenia,2009,male,75+ years,38,48622,78.15,Slovenia2009,NaN,"50,244,793,832",25872,Silent
11523,Hungary,2004,female,75+ years,146,450461,32.41,Hungary2004,NaN,"104,066,609,518",10806,Silent
13909,Kazakhstan,2004,female,75+ years,61,271208,22.49,Kazakhstan2004,NaN,"43,151,647,003",3110,Silent

In [59]:
df_2

[75+ years, 55-74 years, 25-34 years, 35-54 years, 15-24 years, ..., 25-34 years, 15-24 years, 75+ years, 5-14 years, 5-14 years]
Length: 372
Categories (6, object): [5-14 years, 15-24 years, 25-34 years, 35-54 years, 55-74 years, 75+ years]

In [ ]:
# 9. Draw a barplot of # suicides(y) per age-group (x) for 2015

In [ ]:
### 10. Save plot to visualization folder we have created - using plt

In [ ]:
### 11. Push all to your git branch.